"""Add UNIQUE constraint to email column in 'users' table.

Revision ID: 337c474bf192
Revises: 51eb14429a3c
Create Date: 2023-05-04 18:44:36.582878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337c474bf192'
down_revision = '51eb14429a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
